site_name: GoldDigger
site_url: https://cryostem-tools.github.io/GoldDigger
nav:
  - Home: index.md
  - Install: install.md
  - User Guide: user_guide.md
theme:
  name: mkdocs-material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - bash
plugins:
  - search
  - mkdocs-homepage-copier
